### ISSUE TITLE
[Bug]: 404 error on ChromaDB POST APIs

### ISSUE THREAD

**Issue by msanand** [amikos-tech/chromadb-chart#53]
### What happened?

Thank you for providing this helm chart for deploying chromadb on a kubernetes cluster. I managed to make a successful deployment. But when I test the backed APIs on swagger, I notice that the POST APIs, like creating a new collection returns a 404 - Not found error. The GET APIs seem to be working fine, and so are the heartbeat, preflightcheck APIs.

I also checked via code (python) with a HttpClient, and saw the same 404 errors when trying to create a collection. I'm not sure what's going wrong, and what resource is 'not found' during creation. There are no other errors other than the 404, and I don't see any errors in the container logs either.
Appreciate any help here. Thank you!
(ChromaDB version: 0.4.24)

### ChromaDB Version

0.4.3

### Kubernetes Version

1.27.x

### Environment details

Managed kubernetes cluster

**Comment by msanand** [comment]
I've also verified that the client and server versions match - 0.4.24

**Comment by tazarov** [comment]
@msanand, thanks for using the chart :). What endpoint are you using exactly? It should be `POST /api/v1/collections` for creating a collection.

**Comment by msanand** [comment]
@tazarov yes, that's the one I'm using. Infact, I'm running the API from the built-in swagger interface available at /docs endpoint, and still get a 404 on POSTs.
I'm unable to figure out why only POST calls are returning a 404. And which resource is not found exactly. 
Could there be something to do with persistence? Do I have to do anything specific for the PV and PVC to work fine within my cluster?

**Comment by tazarov** [comment]
@msanand, can this be an ingress config you have?

**Comment by msanand** [comment]
@tazarov you were absolutely right. the issue was with the istio ingress configuration where only GET access was provided. Fixing that solved the problem. All good now. Thanks for your support! I will close this issue now.

**Comment by tazarov** [comment]
@msanand, glad you figured it out. Do you think it would be useful for me to add an example of istio ingress?

**Comment by msanand** [comment]
@tazarov Sorry, I seem to have missed your question. Its not directly related to the helm chart or chromadb. It was an oversight on my part when configuring an istio virtual service, so I don't see a need for any documentation update from your side. Thanks for the support again!
