### ISSUE TITLE
[Bug]: Updating any value causes the auth token to be recreated

### ISSUE THREAD

**Issue by dpkirchner** [amikos-tech/chromadb-chart#71]
### What happened?

I changed `resources.requests.memory` and then applied the helm chart change (using opentofu, `helm_release`) and saw that the `chromadb-auth` secret was updated, breaking auth for my application. I don't think this is specific to opentofu, I'm seeing folks on SO talk about this being an issue with regular or helm and using `randAlphaNum`.

I suggest/request a new value that allows us to pass an existing `Secret` k8s resource so we may manage it outside of the chart.

### ChromaDB Version

0.4.14

### Kubernetes Version

1.24.x

### Environment details

GKE, OpenTofu, helm provider 2.14.0.

### Logs, Kubectl output, Manifests, etc.

```shell
resource "helm_release" "chromadb" {
  name       = "chromadb"
  chart      = "chromadb"
  repository = "https://amikos-tech.github.io/chromadb-chart/"
  version    = "v0.1.20"

  namespace = "default"

  values = [<<EOF
chromadb:
  dataVolumeSize: 10Gi
resources:
  requests:
    cpu: 150m
    memory: 2Gi
EOF
]
}
```
```

**Comment by tazarov** [comment]
Hey @dpkirchner, thanks for reporting this. You are right that this is not specific to kubernetes distro, but rather originates from the way the chart generates the unique password.

I'll reproduce and fix it asap.
